ci: check_compliance: workaround junitparser encoding=utf-8 and mode=wb
About 5 months ago, some code was added to junitparser that produces a
warning in Python, which is then converted to an error in CI.

https://github.com/weiwei/junitparser/commit/\
5f8ee5033ae176025e9b09ee4905837da78b4b4d

```
write_xml
    with open(file_or_filename, encoding="utf-8", mode="wb") as xmlfile:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: binary mode doesn't take an encoding argument
```

https://github.com/tenstorrent/tt-zephyr-platforms/actions/runs/\
15831995408/job/44626692874?pr=344

Use a commit slightly preceding this change to avoid the warning.

Signed-off-by: Chris Friedt <cfriedt@tenstorrent.com>