boards: tt_blackhole: galaxy: delete blupdate and dmfwimg partitions
Delete partitions for blupdate and dmfwimg, since building with those
nodes present causes `tt_boot_fs.py mkfs` to fail.

```
Exception: path .../build/mcuboot-bl2/zephyr/zephyr.bin is not a file
```

Signed-off-by: Chris Friedt <cfriedt@tenstorrent.com>